# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: 'signados/jsexpresslogin' 

stages:
- stage: Build
  displayName: Build image and push Docker image
  jobs:
  - job: Build
    displayName: Build and push Docker image
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DockerCompose@0
      displayName: 'Build Docker Compose for server'
      inputs:
        action: 'Run a Docker Compose command'
        dockerComposeFile: '**/compose.yaml'  # Ruta al docker-compose.yml
        projectName: 'jsexpresslogin'
        dockerComposeCommand: 'build' 
        additionalImageTags: |
          $(imageName):$(tag)  # Etiqueta la imagen con el nombre y la versión únicos

    # Paso 3: Subir la imagen construida a Docker Hub
    - task: Docker@2
      displayName: 'Push Docker image to Docker Hub'
      inputs:
        command: 'push'
        repository: $(imageName)  # Nombre de la imagen en Docker Hub
        tags: |
          latest  # Especifica las etiquetas, puedes usar $(Build.BuildId) para versiones únicas
        containerRegistry: 'dockerhub-service-connection'  

